### ISSUE TITLE
Invalid schema

### ISSUE THREAD

**Issue by VladimirCores** [romucci/boilerplate-vue-apollo-graphql-mongodb#1]
After npm install inside server folder I run next:  npm run start

And have this error:

> boilerplate-vue-apollo-graphql-express-mongodb-server-side@1.0.0 start /Users/vladimir.minkin/Documents/Projects/Personal/Vue/boilerplate-vue-apollo-graphql-mongodb/server
> babel-watch src/server.js
Error connecting to database: Error: Invalid schema, expected `mongodb` or `mongodb+srv`
Server started in this URL: http://localhost:undefined/graphiql

**Comment by romucci** [comment]
Oh, now I know why, you didn't provide a .env in the main directory.

you need to put something like 

DB_USER=blabla
DB_PASS=FDJKG
PORT=3000

**Comment by romucci** [comment]
You will also need to determine your URI for the Apollo Client, the MongoDB connection string and a .env file in the server folder .

As the docs say.
