### ISSUE TITLE
install instructions

### ISSUE THREAD

**Issue by tvogt** [romucci/boilerplate-vue-apollo-graphql-mongodb#2]
Looks like a great project, but needs better install instructions. For example, what are the required key files for HTTP2 setup? How to properly start the server and build the client? Just npm start or somethign else?

**Comment by romucci** [comment]
Well, you need to dive into certifications, you need a certificate for HTTP2, you can create a dummy one with OpenSSL :D, you clearly just have to install the dependencies, and then start the server and client up, the client is a normal Vue CLI created app, you run npm build and then if you want to use it in a dist folder in the server you can use serve static from express ❤️

**Comment by tvogt** [comment]
That all probably makes sense to someone already familiar with all the tools. I'm familiar with some of them, but not all, so I am missing some pieces of the puzzle.

**Comment by romucci** [comment]
Well I have to revisit some things, I'll do it when I have time, big finals these couple weeks 🤕

**Comment by romucci** [comment]
Well I have done my best to explain things better and I have made the template better! 💃
